/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;

import View.Login;

public class App {

    public static void main(String[] args) {
        new Login().setVisible(true);
    }
}
