/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;

import View.Management;
//import View.SplashScreen;

public class App {

    public static void main(String[] args) {
        new Management().setVisible(true);
//        new SplashScreen().setVisible(true);
    }
}
