/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.DatabaseConnection;
import Model.RoomTableModel;
import Model.TransactionTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marvi
 */
public class TransactionDetails extends javax.swing.JFrame {
    
    private TransactionTableModel model;
    /**
     * Creates new form GuestList
     */
    public TransactionDetails() {
        initComponents();
        this.model = new TransactionTableModel();
        fetchTransactionData();
    }
    
    private void fetchTransactionData() {
        try {
            ResultSet rs = model.fetchTransactionDetails();
            DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
            tableModel.setRowCount(0);

            while (rs.next()) {
                String guestName = rs.getString("firstName") + " " + rs.getString("lastName");
                String roomNumber = rs.getString("roomNumber");
                String paymentDate = rs.getString("paymentDate");
                String paymentMethod = rs.getString("paymentMethod");
                String paymentAmount = rs.getString("paymentAmount");
                tableModel.addRow(new Object[]{guestName, roomNumber, paymentDate, paymentMethod, paymentAmount});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error fetching room details: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        minimizeBtn8 = new javax.swing.JButton();
        minimizeBtn10 = new javax.swing.JButton();
        minimizeBtn11 = new javax.swing.JButton();
        minimizeBtn12 = new javax.swing.JButton();
        minimizeBtn13 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        minimizeBtn14 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        minimizeBtn15 = new javax.swing.JButton();
        minimizeBtn16 = new javax.swing.JButton();
        minimizeBtn17 = new javax.swing.JButton();
        minimizeBtn20 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(101, 28, 50));

        minimizeBtn8.setBackground(new java.awt.Color(101, 28, 50));
        minimizeBtn8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimizeBtn8.setForeground(new java.awt.Color(255, 255, 255));
        minimizeBtn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking.png"))); // NOI18N
        minimizeBtn8.setText("Bookings");
        minimizeBtn8.setToolTipText("");
        minimizeBtn8.setBorder(null);
        minimizeBtn8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        minimizeBtn8.setIconTextGap(10);
        minimizeBtn8.setInheritsPopupMenu(true);
        minimizeBtn8.setMargin(new java.awt.Insets(5, 5, 5, 5));
        minimizeBtn8.setMaximumSize(new java.awt.Dimension(64, 42));
        minimizeBtn8.setMinimumSize(new java.awt.Dimension(64, 42));
        minimizeBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtn8ActionPerformed(evt);
            }
        });

        minimizeBtn10.setBackground(new java.awt.Color(101, 28, 50));
        minimizeBtn10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimizeBtn10.setForeground(new java.awt.Color(255, 255, 255));
        minimizeBtn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        minimizeBtn10.setText("Dashboard");
        minimizeBtn10.setBorder(null);
        minimizeBtn10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        minimizeBtn10.setIconTextGap(10);
        minimizeBtn10.setInheritsPopupMenu(true);
        minimizeBtn10.setMargin(new java.awt.Insets(5, 5, 5, 5));
        minimizeBtn10.setMaximumSize(new java.awt.Dimension(64, 42));
        minimizeBtn10.setMinimumSize(new java.awt.Dimension(64, 42));
        minimizeBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtn10ActionPerformed(evt);
            }
        });

        minimizeBtn11.setBackground(new java.awt.Color(101, 28, 50));
        minimizeBtn11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimizeBtn11.setForeground(new java.awt.Color(255, 255, 255));
        minimizeBtn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rooms.png"))); // NOI18N
        minimizeBtn11.setText("Rooms");
        minimizeBtn11.setToolTipText("");
        minimizeBtn11.setBorder(null);
        minimizeBtn11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        minimizeBtn11.setIconTextGap(10);
        minimizeBtn11.setInheritsPopupMenu(true);
        minimizeBtn11.setMargin(new java.awt.Insets(5, 5, 5, 5));
        minimizeBtn11.setMaximumSize(new java.awt.Dimension(64, 42));
        minimizeBtn11.setMinimumSize(new java.awt.Dimension(64, 42));
        minimizeBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtn11ActionPerformed(evt);
            }
        });

        minimizeBtn12.setBackground(new java.awt.Color(101, 28, 50));
        minimizeBtn12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimizeBtn12.setForeground(new java.awt.Color(255, 255, 255));
        minimizeBtn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guest.png"))); // NOI18N
        minimizeBtn12.setText("Guests");
        minimizeBtn12.setBorder(null);
        minimizeBtn12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        minimizeBtn12.setIconTextGap(10);
        minimizeBtn12.setInheritsPopupMenu(true);
        minimizeBtn12.setMargin(new java.awt.Insets(5, 5, 5, 5));
        minimizeBtn12.setMaximumSize(new java.awt.Dimension(64, 42));
        minimizeBtn12.setMinimumSize(new java.awt.Dimension(64, 42));
        minimizeBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtn12ActionPerformed(evt);
            }
        });

        minimizeBtn13.setBackground(new java.awt.Color(101, 28, 50));
        minimizeBtn13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimizeBtn13.setForeground(new java.awt.Color(255, 255, 255));
        minimizeBtn13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaction.png"))); // NOI18N
        minimizeBtn13.setText("Transactions");
        minimizeBtn13.setToolTipText("");
        minimizeBtn13.setBorder(null);
        minimizeBtn13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        minimizeBtn13.setIconTextGap(10);
        minimizeBtn13.setInheritsPopupMenu(true);
        minimizeBtn13.setMargin(new java.awt.Insets(5, 5, 5, 5));
        minimizeBtn13.setMaximumSize(new java.awt.Dimension(64, 42));
        minimizeBtn13.setMinimumSize(new java.awt.Dimension(64, 42));
        minimizeBtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtn13ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        minimizeBtn14.setBackground(new java.awt.Color(101, 28, 50));
        minimizeBtn14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        minimizeBtn14.setForeground(new java.awt.Color(255, 255, 255));
        minimizeBtn14.setText("Log out");
        minimizeBtn14.setInheritsPopupMenu(true);
        minimizeBtn14.setMargin(new java.awt.Insets(5, 14, 5, 14));
        minimizeBtn14.setMaximumSize(new java.awt.Dimension(64, 42));
        minimizeBtn14.setMinimumSize(new java.awt.Dimension(64, 42));
        minimizeBtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtn14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeBtn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeBtn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeBtn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeBtn12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeBtn13, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(minimizeBtn14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(minimizeBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minimizeBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minimizeBtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minimizeBtn11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minimizeBtn13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minimizeBtn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel2.setBackground(new java.awt.Color(101, 28, 50));

        closeBtn.setBackground(new java.awt.Color(179, 139, 78));
        closeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        closeBtn.setToolTipText("");
        closeBtn.setFocusCycleRoot(true);
        closeBtn.setMargin(new java.awt.Insets(5, 14, 5, 14));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(closeBtn)
                .addGap(15, 15, 15))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        minimizeBtn15.setBackground(new java.awt.Color(101, 28, 50));
        minimizeBtn15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        minimizeBtn15.setForeground(new java.awt.Color(255, 255, 255));
        minimizeBtn15.setText("GUESTS DETAILS");
        minimizeBtn15.setInheritsPopupMenu(true);
        minimizeBtn15.setMargin(new java.awt.Insets(5, 14, 5, 14));
        minimizeBtn15.setMaximumSize(new java.awt.Dimension(64, 42));
        minimizeBtn15.setMinimumSize(new java.awt.Dimension(64, 42));
        minimizeBtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtn15ActionPerformed(evt);
            }
        });

        minimizeBtn16.setBackground(new java.awt.Color(101, 28, 50));
        minimizeBtn16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        minimizeBtn16.setForeground(new java.awt.Color(255, 255, 255));
        minimizeBtn16.setText("ADD");
        minimizeBtn16.setInheritsPopupMenu(true);
        minimizeBtn16.setMargin(new java.awt.Insets(5, 14, 5, 14));
        minimizeBtn16.setMaximumSize(new java.awt.Dimension(64, 42));
        minimizeBtn16.setMinimumSize(new java.awt.Dimension(64, 42));
        minimizeBtn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtn16ActionPerformed(evt);
            }
        });

        minimizeBtn17.setBackground(new java.awt.Color(101, 28, 50));
        minimizeBtn17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        minimizeBtn17.setForeground(new java.awt.Color(255, 255, 255));
        minimizeBtn17.setText("CANCEL");
        minimizeBtn17.setInheritsPopupMenu(true);
        minimizeBtn17.setMargin(new java.awt.Insets(5, 14, 5, 14));
        minimizeBtn17.setMaximumSize(new java.awt.Dimension(64, 42));
        minimizeBtn17.setMinimumSize(new java.awt.Dimension(64, 42));
        minimizeBtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtn17ActionPerformed(evt);
            }
        });

        minimizeBtn20.setBackground(new java.awt.Color(101, 28, 50));
        minimizeBtn20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        minimizeBtn20.setForeground(new java.awt.Color(255, 255, 255));
        minimizeBtn20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        minimizeBtn20.setInheritsPopupMenu(true);
        minimizeBtn20.setMargin(new java.awt.Insets(5, 14, 5, 14));
        minimizeBtn20.setMaximumSize(new java.awt.Dimension(64, 42));
        minimizeBtn20.setMinimumSize(new java.awt.Dimension(64, 42));
        minimizeBtn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtn20ActionPerformed(evt);
            }
        });

        jTextField2.setText("Search");
        jTextField2.setToolTipText("");
        jTextField2.setMargin(new java.awt.Insets(5, 6, 5, 6));

        jTable2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Guest Name", "Booking ID", "Payment Date", "Payment Method", "Payment Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(40);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizeBtn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(minimizeBtn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(minimizeBtn17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minimizeBtn20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minimizeBtn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minimizeBtn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(minimizeBtn17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(minimizeBtn20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 92, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeBtn8ActionPerformed

    private void minimizeBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeBtn10ActionPerformed

    private void minimizeBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeBtn11ActionPerformed

    private void minimizeBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeBtn12ActionPerformed

    private void minimizeBtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtn13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeBtn13ActionPerformed

    private void minimizeBtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtn14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeBtn14ActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void minimizeBtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtn15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeBtn15ActionPerformed

    private void minimizeBtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtn16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeBtn16ActionPerformed

    private void minimizeBtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtn17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeBtn17ActionPerformed

    private void minimizeBtn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtn20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeBtn20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton minimizeBtn10;
    private javax.swing.JButton minimizeBtn11;
    private javax.swing.JButton minimizeBtn12;
    private javax.swing.JButton minimizeBtn13;
    private javax.swing.JButton minimizeBtn14;
    private javax.swing.JButton minimizeBtn15;
    private javax.swing.JButton minimizeBtn16;
    private javax.swing.JButton minimizeBtn17;
    private javax.swing.JButton minimizeBtn20;
    private javax.swing.JButton minimizeBtn8;
    // End of variables declaration//GEN-END:variables
}
